lib: [
  "_build/install/default/lib/imap/META" {"META"}
  "_build/install/default/lib/imap/opam" {"opam"}
  "_build/install/default/lib/imap/imap.cmi"
  "_build/install/default/lib/imap/imap.cmx"
  "_build/install/default/lib/imap/imap.cmt"
  "_build/install/default/lib/imap/imap.cmti"
  "_build/install/default/lib/imap/imap.mli"
  "_build/install/default/lib/imap/imap.ml"
  "_build/install/default/lib/imap/imap.cma"
  "_build/install/default/lib/imap/imap.cmxa"
  "_build/install/default/lib/imap/imap.a"
  "_build/install/default/lib/imap/imap.cmxs"
]
doc: [
  "_build/install/default/doc/imap/README.md"
  "_build/install/default/doc/imap/LICENSE"
  "_build/install/default/doc/imap/CHANGES"
]
